server:
  port: 31001
spring:
  application:
    name: XC-SERVICE-MANAGE-CMS
  data:
    mongodb:
      uri: mongodb://root:070313@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  freemarker:
    cache: false
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试

eureka:
  client:
    service-url:  # Eureka客户端与Eureka服务端的交互地址，高可用配置对方的地址，单击状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://eureka01:50101/eureka/,http://eureka02:50102/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}